export const types = () => [
  {
    key: 'Odour type',
    value: 'Odour type',
    label: 'Odour type',
    count: 0,
    condition: false,
    items: [
      'Other',
      'Ammonia',
      'Forest / Trees / Nature',
      'Waste water',
      'Alcohol',
      'Chimney (burnt wood)',
      'Organic fertilizers (manure/slurry)',
      'Amines',
      'Plastic',
      'Chemical',
      'Leachate',
      'Bread / Cookies',
      'Fresh waste',
      'Flowers',
      'Decomposed waste',
      'No Odour',
      'Rotten eggs',
      'Fuel',
      'Sewage',
      'Urine',
      'Oil / Petrochemical',
      'Waste bin',
      'Fresh grass',
      'Sweat',
      'Humidity / Wet soil',
      'Cabbage soup',
      'Traffic',
      'Cocoa',
      'Food',
      'Wood',
      'Animal feed',
      'Glue / Adhesive',
      'Sea',
      'Sludge',
      'Mint / Rosemary / Lavander',
      'Asphalt / Rubber',
      'Biogas',
      'Gas',
      'Metal',
      'Perfume',
      'Aroma / Flavour',
      'Paint',
      'Fruit',
      'Bakeries',
      'Fat / Oil',
      "I don't know",
      'Coffee',
      'Cooked meat',
      'Waste truck',
      'Ammines',
      'Fish',
      'Ketone / Ester / Acetate / Ether',
      'Dead animal',
      'Animal food',
      'Milk / Dairy',
      'Sulphur',
      'Malt / Hop',
      'Biofilter',
      'Raw meat',
      'Chlorine',
      'Leather',
    ],
  }, {
    key: 'Odour intensity',
    value: 'Odour intensity',
    label: 'Odour intensity',
    count: 0,
    condition: false,
    items: [
      'Very weak',
      'Weak',
      'Noticeable',
      'Strong',
      'Very strong',
      'Extremely strong',
    ],
  }, {
    key: 'Hedonic tone',
    value: 'Hedonic tone',
    label: 'Hedonic tone',
    count: 0,
    condition: false,
    items: [
      'Extremely unpleasant',
      'Very unpleasant',
      'Slightly unpleasant',
      'Unpleasant',
      'Neutral',
      'Pleasant',
      'Slightly pleasant',
      'Very pleasant',
      'Extremely pleasant'
    ]
  }
]


// types = [
//   'Odour type',
//   'Odour intensity',
//   'Hedonic tone',
//   'PM1',
//   'PM2.5',
//   'PM10',
//   'Temperature',
//   'Humidity',
//   'Pressure',
//   'CO2',
//   'CO2 Temperature',
//   'CO2 Humidity',
//   'Battery voltage',
// ].map(i => ({key: i, value: i, label: i}))
